### ISSUE TITLE
RTTY Decoding

### ISSUE THREAD

**Issue by juliantech5** [jgromes/KiteLib#2]
Hey, I am trying to decode the RTTY example using MMTTY and FLDigi but I cannot seem to get it to successfully decode. I suspect this is due to it being ASCII and not Baudot ITA2, do you have an implementation for ITA2 or can you share how to decode the rtty? thanks!

**Comment by jgromes** [comment]
Are you using the latest version of the library? ITA2 support was added in 4fecd8c07390c4e1cd3a03668fb85f50d61083e5

I only have RTL dongle, so I'm using SDRConsole v2 to receive RTTY. SDRConsole has configurable baud rate, shift and number of data bits (5 - 8) so it can receive ASCII as well as ITA2.

**Comment by juliantech5** [comment]
Thanks, issue solved :)

**Comment by jgromes** [comment]
Glad I could help :) 

So what are you using now? ITA2 + MMTTY or ASCII + SDRConsole?

**Comment by juliantech5** [comment]
For now ITA2 + FLDIGI & RTTY
:) Thanks!
